### ISSUE TITLE
Issue using with tf.keras

### ISSUE THREAD

**Issue by ashwan1** [titu1994/keras-attention-augmented-convs#4]
Hello,

I am trying to adapt this layer for tf.keras. I made few changes, but got stuck on one. Can you please help. Thanks in advance.

Here is stacktrace:

```
Traceback (most recent call last):
  File "aacn_b0_tf.py", line 926, in <module>
    train_images_dir, test_images_dir, batch_size, lr, labels)
  File "aacn_b0_tf.py", line 830, in run
    model = get_model(img_size, n_channels, n_classes, dropout_rate, leak)
  File "aacn_b0_tf.py", line 801, in get_model
    x = bottleneck_block(x, 112, 192, 5, 2, 'block6_0', use_aacn=True)
  File "aacn_b0_tf.py", line 750, in bottleneck_block
    i, int(input_filters * expand_ratio), depth_k=24, depth_v=24)
  File "/home/ashwanipandey/kaggle/aptos19-blindness-detection/attn_aug_conv.py", line 306, in augmented_conv2d
    attn_out = _conv_layer(depth_v, kernel_size=(1, 1))(attn_out)
  File "/home/ashwanipandey/kaggle/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 591, in __call__
    self._maybe_build(inputs)
  File "/home/ashwanipandey/kaggle/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1881, in _maybe_build
    self.build(input_shapes)
  File "/home/ashwanipandey/kaggle/venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 153, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```

It seems like `self.depth_v` is becoming `None` somewhere, but I cannot figure out where and why.

**Comment by titu1994** [comment]
Because of the multiple dot products, the tensorflow tensor loses shape information, and Keras can't use K.int_shape() to query the channel dimension. It should be possible to follow the shapes and use x.set_shape(...) where x is the tensor just before where this error occurs.

**Comment by ashwan1** [comment]
Thanks, I'll try doing that and will update.

**Comment by noahtren** [comment]
I ran into this same problem using tf.keras with TensorFlow 2 and solved it by adding this line at the very end of the `call` function:
```python
attn_out.set_shape(self.compute_output_shape(self._shape))
```

Happy to open a PR, but not sure what the effect is if for those just using Keras.

**Comment by titu1994** [comment]
Please open a PR. Keras proper is on maintainance mode and we will prioritize tf.keras.

**Comment by noahtren** [comment]
Opened PR https://github.com/titu1994/keras-attention-augmented-convs/pull/7!

**Comment by titu1994** [comment]
PR #7 merged.
